### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by kokokenada** [fanout/django-eventstream#119]
my base.txt that lists the requirements are:

```pytz==2023.3  # https://github.com/stub42/pytz
python-slugify==8.0.1  # https://github.com/un33k/python-slugify
Pillow==9.5.0  # https://github.com/python-pillow/Pillow
argon2-cffi==21.3.0  # https://github.com/hynek/argon2_cffi
whitenoise==6.4.0  # https://github.com/evansd/whitenoise
redis==4.5.4  # https://github.com/redis/redis-py
hiredis==2.2.2  # https://github.com/redis/hiredis-py
uvicorn[standard]==0.22.0  # https://github.com/encode/uvicorn
asgiref==3.6.0
channels==3.0.5
django-eventstream==4.5.1

# Django
# ------------------------------------------------------------------------------
django==4.2  # pyup: < 4.2  # https://www.djangoproject.com/
django-environ==0.10.0  # https://github.com/joke2k/django-environ
django-model-utils==4.3.1  # https://github.com/jazzband/django-model-utils
django-allauth==0.54.0  # https://github.com/pennersr/django-allauth
django-crispy-forms==2.0  # https://github.com/django-crispy-forms/django-crispy-forms
crispy-bootstrap5==0.7  # https://github.com/django-crispy-forms/crispy-bootstrap5
django-redis==5.2.0  # https://github.com/jazzband/django-redis
graphene-django==3.0.0
django-cors-headers==3.14.0
django-graphql-jwt==0.3.4
# django_filters==0.23.2
# graphene_django_filter==0.6.4

# Langchain stuff
langchain[llms]==0.0.174
```
Running `pip install -r packages/server/requirements/local.txt` results in:

```
ERROR: Cannot install django-eventstream and werkzeug[watchdog]==2.3.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    werkzeug[watchdog] 2.3.1 depends on werkzeug 2.3.1 (from https://files.pythonhosted.org/packages/9b/5a/6259e936ce9b9043293dd8473943f5e6bba244c2cb6e3e5354406dfb0700/Werkzeug-2.3.1-py3-none-any.whl (from https://pypi.org/simple/werkzeug/) (requires-python:>=3.8))
    django-grip 3.2.0 depends on Werkzeug<2.3 and >=1.0
    werkzeug[watchdog] 2.3.1 depends on werkzeug 2.3.1 (from https://files.pythonhosted.org/packages/9b/5a/6259e936ce9b9043293dd8473943f5e6bba244c2cb6e3e5354406dfb0700/Werkzeug-2.3.1-py3-none-any.whl (from https://pypi.org/simple/werkzeug/) (requires-python:>=3.8))
    django-grip 3.1.0 depends on Werkzeug<2.1 and >=1.0
    werkzeug[watchdog] 2.3.1 depends on werkzeug 2.3.1 (from https://files.pythonhosted.org/packages/9b/5a/6259e936ce9b9043293dd8473943f5e6bba244c2cb6e3e5354406dfb0700/Werkzeug-2.3.1-py3-none-any.whl (from https://pypi.org/simple/werkzeug/) (requires-python:>=3.8))
    django-grip 3.0.0 depends on Werkzeug<1 and >=0.12

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
Should this package update its requirements? But I'm confused as I don't see requirements in this repo. (Did I miss it?)

An attempted workaround of removing the version (change `django-eventstream==4.5.1` to `django-eventstream`) resulted in:

```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/mh/x0ycprzx3h1_1vr886_n__ww0000gn/T/pip-install-qunc7urm/django-eventstream_eedda5c1d22c4cc096150371f11a714c/setup.py", line 4, in <module>
          with open(os.path.join(os.path.dirname(__file__), 'README.md')) as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/mh/x0ycprzx3h1_1vr886_n__ww0000gn/T/pip-install-qunc7urm/django-eventstream_eedda5c1d22c4cc096150371f11a714c/README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by jkarneges** [comment]
Thanks for the report. I've published django-grip 3.3.0 with a relaxed Werkzeug requirement which should fix this.
